### ISSUE TITLE
Transform Python programs into batch files and more

### ISSUE THREAD

**Issue by Exorcism0666** [Krummers/Intermezzo-Scripts#11]
There is a way to do this with PyInstaller, which allows you to transform python programs into .exe programs for windows (and it also works for MacOS and Ubuntu (with their own extension)).

The advantage is that it will avoid having to install a lot of python modules (but it will have to install 7zip).

Unfortunately I don't know how to do it since there are two python programs and for the moment I can only compile one program with the knowledge I have but I can already give some hints to avoid problems.

https://github.com/dancepartyonline/patcher/blob/main/.github/workflows/build.yml (there is first this workflow that allows to compile a single python program for example)

https://github.com/RiiConnect24/RiiTag-RPC (and there is also this repo that managed to compile several python and other programs with the file "riitag-rpc.spec" and also the available worflows "build.yml").

**Comment by Riddim-GLiTCH** [comment]
I like this idea. It would make it easier to call from PATH, allowing the user to just point at an output folder for building in. 
`C:\Users\janedoe> intermezzo-patcher -d c:/users/janedoe/documents/intermezzos` would be an example of the command used, with `-d` being the Destination option. As a dolphin user, I can see `-emu` being used for the default dolphin riivolution path.

**Comment by Krummers** [comment]
Not useful, since most people that use this have Python installed.
