### ISSUE TITLE
File extraction bug

### ISSUE THREAD

**Issue by Exorcism0666** [Krummers/Intermezzo-Scripts#34]
**Describe the bug:**
Unable to extract the file "mkw-intermezzo-XXXX-XX-XX.txz", the problem would come from line 186 of "Intermezzo.py" using python's "subprocess" module

**Operating system:**
 - Windows (WSL2)

**Present files:**
![image](https://github.com/Krummers/Intermezzo-Scripts/assets/46537034/a5e053e8-9c0a-4dc1-baf8-2d67ab3c0bd0)

**Script Crash:**
![image](https://cdn.discordapp.com/attachments/865485410204778506/1132246555991232584/image.png)

**Comment by Krummers** [comment]
Fixed by using lists instead of strings in `sp.run`.
