### ISSUE TITLE
Delete `__pycache__` folders after building

### ISSUE THREAD

**Issue by Exorcism0666** [Krummers/Intermezzo-Scripts#37]

**Comment by Krummers** [comment]
`__pycache__` is supposed to make the scripts faster. Why would we want this?

**Comment by Exorcism0666** [comment]
Ah welp, nvm, I thought that even by erasing the file it would not go faster

**Comment by Krummers** [comment]
I could make this a setting if you really want it

**Comment by Exorcism0666** [comment]
well it's as you want LMAO

**Comment by Krummers** [comment]
Setting is implemented in the patcher

**Comment by Krummers** [comment]
Implemented in settings
