### ISSUE TITLE
Add option to download latest Intermezzo

### ISSUE THREAD

**Issue by swampatha** [Krummers/Intermezzo-Scripts#50]
**Describe the feature:**
To save time when patching a regular Intermezzo, add an option to only check for the latest Intermezzo and stop checking when one is found instead of checking for all possible Intermezzos over the past three months.

**Project:**
Patcher

**Comment by Krummers** [comment]
This would be added in the form of a single question at the start of the script. It would scan the website for the latest regular Intermezzo, which should take a maximum of 7 × ~2 seconds. (Knowing Wiimm, 14 × ~2 seconds is more realistic.)

Is an option to turn off this question necessary?

**Comment by swampatha** [comment]
For most cases it shouldn't be necessary, but in the event of something like a vacation preventing you from hosting for a week or so we may need to build older versions. Maybe at the start of the script you could ask the user if they want to check for a specific date, and it'll check for that first, and if it doesn't exist then just pull the latest build?

**Comment by Krummers** [comment]
I will implement #39 first before doing this. If the drastic speedup after that is still not enough, I can consider this.

**Comment by Krummers** [comment]
Irrelevant because of #39
